USE `e-commerce`;

SELECT * FROM USERS;

SELECT * FROM FOOD;

SELECT * FROM PRODUCT;

SELECT U_NAME FROM USERS WHERE U_ID = 2;

SELECT * FROM USERS WHERE U_AGE > 20 AND F_ID IS NOT NULL;
 
SELECT * FROM USERS WHERE U_NAME = 'Harshit' OR U_QUANTITY = 4; 

SELECT * FROM USERS WHERE U_NAME LIKE'%ay';

SELECT * FROM USERS WHERE U_AGE BETWEEN 20 AND 25;

SELECT * FROM USERS ORDER BY U_NAME DESC;

SELECT * FROM USERS ORDER BY U_QUANTITY, U_NAME;

SELECT * FROM USERS ORDER BY U_ID DESC LIMIT 3;



