CREATE SCHEMA `e-commerce`;

USE `e-commerce`;

CREATE TABLE PRODUCT (
 P_ID INT PRIMARY KEY,
 P_NAME VARCHAR(50) NOT NULL,
 PRICE DOUBLE NOT NULL
);

CREATE TABLE FOOD (
	F_ID INT PRIMARY KEY,
    F_NAME VARCHAR(40) NOT NULL,
    F_PRICE DOUBLE NOT NULL
);

CREATE TABLE USERS (
	U_ID INT PRIMARY KEY AUTO_INCREMENT,
    U_NAME VARCHAR(50) NOT NULL,
    U_AGE INT CHECK(U_AGE >=18) NOT NULL,
    U_QUANTITY INT NOT NULL,
    P_ID INT,
    F_ID INT,
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID),
    FOREIGN KEY (F_ID) REFERENCES FOOD(F_ID)
);
